Update docker.yaml

diff --git a/.github/workflows/docker.yaml b/.github/workflows/docker.yaml
--- a/.github/workflows/docker.yaml
+++ b/.github/workflows/docker.yaml
@@ -6,142 +6,142 @@ on:
     - cron: '0 6,12 * * *'
 
 env:
-  ALIYUN_REGISTRY: ${{ secrets.ALIYUN_REGISTRY }}
-  ALIYUN_NAME_SPACE: ${{ secrets.ALIYUN_NAME_SPACE }}
-  ALIYUN_REGISTRY_USER: ${{ secrets.ALIYUN_REGISTRY_USER }}
-  ALIYUN_REGISTRY_PASSWORD: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
-  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
-  TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
+  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
+  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
+  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
+  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"
+  TG_BOT_TOKEN: "${{ secrets.TG_BOT_TOKEN }}"
+  TG_CHAT_ID: "${{ secrets.TG_CHAT_ID }}"
 
 jobs:
   build:
     name: 拉取镜像并推送至阿里云
     runs-on: ubuntu-latest
     steps:
-      - name: 初始化时间与日志
-        run: |
-          echo "start_time=$(date +%s)" >> $GITHUB_ENV
-          > new_images_success.log
-          > new_images_failed.log
+    - name: 初始化时间与日志
+      run: |
+        echo "start_time=$(date +%s)" >> $GITHUB_ENV
+        > new_images_success.log
+        > new_images_failed.log
 
-      - name: 清理磁盘空间前的状态
-        run: df -hT
+    - name: 清理磁盘空间前的状态
+      run: df -hT
 
-      - name: 最大化构建空间
-        uses: easimon/maximize-build-space@master
-        with:
-          root-reserve-mb: 2048
-          swap-size-mb: 128
-          remove-dotnet: 'true'
-          remove-haskell: 'true'
-          build-mount-path: '/var/lib/docker/'
+    - name: 最大化构建空间
+      uses: easimon/maximize-build-space@master
+      with:
+        root-reserve-mb: 2048
+        swap-size-mb: 128
+        remove-dotnet: 'true'
+        remove-haskell: 'true'
+        build-mount-path: '/var/lib/docker/'
 
-      - name: 重启 Docker 服务
-        run: sudo service docker restart
+    - name: 重启 Docker 服务
+      run: sudo service docker restart
 
-      - name: 获取代码
-        uses: actions/checkout@v4
+    - name: 获取代码
+      uses: actions/checkout@v4
 
-      - name: 配置 Buildx
-        uses: docker/setup-buildx-action@v3
+    - name: 配置 Buildx
+      uses: docker/setup-buildx-action@v3
 
-      - name: 构建并推送镜像到阿里云
-        run: |
-          docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY
+    - name: 构建并推送镜像到阿里云
+      run: |
+        docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY
 
-          declare -A duplicate_images
-          declare -A temp_map
+        declare -A duplicate_images
+        declare -A temp_map
 
-          while IFS= read -r line || [ -n "$line" ]; do
-              [[ -z "$line" ]] && continue
-              [[ "$line" =~ ^\s*# ]] && continue
-              image=$(echo "$line" | awk '{print $NF}')
-              image="${image%%@*}"
-              image_name_tag=$(echo "$image" | awk -F'/' '{print $NF}')
-              name_space=$(echo "$image" | awk -F'/' '{if (NF==3) print $2; else if (NF==2) print $1; else print ""}')
-              name_space="${name_space}_"
-              image_name=$(echo "$image_name_tag" | awk -F':' '{print $1}')
-              if [[ -n "${temp_map[$image_name]}" ]]; then
-                  if [[ "${temp_map[$image_name]}" != $name_space ]]; then
-                      duplicate_images[$image_name]="true"
-                  fi
-              else
-                  temp_map[$image_name]=$name_space
-              fi
-          done < images.txt
+        while IFS= read -r line || [ -n "$line" ]; do
+            [[ -z "$line" ]] && continue
+            [[ "$line" =~ ^\s*# ]] && continue
+            image=$(echo "$line" | awk '{print $NF}')
+            image="${image%%@*}"
+            image_name_tag=$(echo "$image" | awk -F'/' '{print $NF}')
+            name_space=$(echo "$image" | awk -F'/' '{if (NF==3) print $2; else if (NF==2) print $1; else print ""}')
+            name_space="${name_space}_"
+            image_name=$(echo "$image_name_tag" | awk -F':' '{print $1}')
+            if [[ -n "${temp_map[$image_name]}" ]]; then
+                if [[ "${temp_map[$image_name]}" != $name_space ]]; then
+                    duplicate_images[$image_name]="true"
+                fi
+            else
+                temp_map[$image_name]=$name_space
+            fi
+        done < images.txt
 
-          while IFS= read -r line || [ -n "$line" ]; do
-              [[ -z "$line" ]] && continue
-              [[ "$line" =~ ^\s*# ]] && continue
+        while IFS= read -r line || [ -n "$line" ]; do
+            [[ -z "$line" ]] && continue
+            [[ "$line" =~ ^\s*# ]] && continue
 
-              docker pull $line || { echo "$line" >> new_images_failed.log; continue; }
+            docker pull $line || { echo "$line" >> new_images_failed.log; continue; }
 
-              platform=$(echo "$line" | awk -F'--platform[ =]' '{if (NF>1) print $2}' | awk '{print $1}')
-              platform_prefix=""
-              [[ -n "$platform" ]] && platform_prefix="${platform//\//_}_"
+            platform=$(echo "$line" | awk -F'--platform[ =]' '{if (NF>1) print $2}' | awk '{print $1}')
+            platform_prefix=""
+            [[ -n "$platform" ]] && platform_prefix="${platform//\//_}_"
 
-              image=$(echo "$line" | awk '{print $NF}')
-              image="${image%%@*}"
-              image_name_tag=$(echo "$image" | awk -F'/' '{print $NF}')
-              name_space=$(echo "$image" | awk -F'/' '{if (NF==3) print $2; else if (NF==2) print $1; else print ""}')
-              image_name=$(echo "$image_name_tag" | awk -F':' '{print $1}')
-              name_space_prefix=""
-              if [[ -n "${duplicate_images[$image_name]}" && -n "$name_space" ]]; then
-                name_space_prefix="${name_space}_"
-              fi
+            image=$(echo "$line" | awk '{print $NF}')
+            image="${image%%@*}"
+            image_name_tag=$(echo "$image" | awk -F'/' '{print $NF}')
+            name_space=$(echo "$image" | awk -F'/' '{if (NF==3) print $2; else if (NF==2) print $1; else print ""}')
+            image_name=$(echo "$image_name_tag" | awk -F':' '{print $1}')
+            name_space_prefix=""
+            if [[ -n "${duplicate_images[$image_name]}" && -n "$name_space" ]]; then
+              name_space_prefix="${name_space}_"
+            fi
 
-              new_image="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$platform_prefix$name_space_prefix$image_name_tag"
-              docker tag "$image" "$new_image" || { echo "$image" >> new_images_failed.log; continue; }
+            new_image="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$platform_prefix$name_space_prefix$image_name_tag"
+            docker tag "$image" "$new_image" || { echo "$image" >> new_images_failed.log; continue; }
 
-              if docker push "$new_image"; then
-                echo "$new_image" >> new_images_success.log
-              else
-                echo "$image" >> new_images_failed.log
-                continue
-              fi
+            if docker push "$new_image"; then
+              echo "$new_image" >> new_images_success.log
+            else
+              echo "$image" >> new_images_failed.log
+              continue
+            fi
 
-              docker rmi "$image" || true
-              docker rmi "$new_image" || true
-          done < images.txt
+            docker rmi "$image" || true
+            docker rmi "$new_image" || true
+        done < images.txt
 
-      - name: 发送构建状态和镜像列表到 Telegram
-        if: always()
-        run: |
-          end_time=$(date +%s)
-          duration_sec=$(( end_time - start_time ))
-          duration_min=$(( duration_sec / 60 ))
-          duration_rem=$(( duration_sec % 60 ))
-          DURATION="${duration_min}分${duration_rem}秒"
+    - name: 发送构建状态和镜像列表到 Telegram
+      if: always()
+      run: |
+        end_time=$(date +%s)
+        duration_sec=$(( end_time - start_time ))
+        duration_min=$(( duration_sec / 60 ))
+        duration_rem=$(( duration_sec % 60 ))
+        DURATION="${duration_min}分${duration_rem}秒"
 
-          STATUS="${{ job.status }}"
+        STATUS="${{ job.status }}"
 
-          MSG="🧱 *GitHub Actions Docker 构建任务*
+        MSG="<b>🧱 GitHub Actions Docker 构建任务</b>
 ⏱️ 耗时：$DURATION
 📅 时间：$(date "+%Y-%m-%d %H:%M:%S")
 ✅ 状态：$STATUS
 
 "
 
-          if [ -s new_images_success.log ]; then
-            MSG+="📦 *成功推送的镜像：*
+        if [ -s new_images_success.log ]; then
+          MSG+="<b>📦 成功推送的镜像：</b>
 "
-            while read -r line; do
-              MSG+="- $line
+          while read -r line; do
+            MSG+="- $line
 "
-            done < new_images_success.log
-          fi
+          done < new_images_success.log
+        fi
 
-          if [ -s new_images_failed.log ]; then
-            MSG+="
-🚫 *失败的镜像（构建/推送失败）：*
+        if [ -s new_images_failed.log ]; then
+          MSG+="
+<b>🚫 失败的镜像（构建/推送失败）：</b>
 "
-            while read -r line; do
-              MSG+="- $line
+          while read -r line; do
+            MSG+="- $line
 "
-            done < new_images_failed.log
-          fi
+          done < new_images_failed.log
+        fi
 
-          curl -s -X POST "https://api.telegram.org/bot$TG_BOT_TOKEN/sendMessage" \
-            -d chat_id="$TG_CHAT_ID" \
-            -d parse_mode=Markdown \
-            -d text="$MSG"
+        curl -s -X POST "https://api.telegram.org/bot$TG_BOT_TOKEN/sendMessage" \
+          -d chat_id="$TG_CHAT_ID" \
+          -d parse_mode=HTML \
+          -d text="$MSG"
